version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8181:80
    volumes:
      - ./:/var/www/html
    networks:
      - backend

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aerohouse
      MYSQL_USER: mateus
      MYSQL_PASSWORD: secret
    ports:
      - 3307:3306
    networks:
      - backend

networks:
  backend:
    driver: bridge
